env:
    GH_USN: "ENCRYPTED[ac16e568e1b9d2ccd2ffa61e30a7ac810aad59e4486cd08fb44eecf253aa01f8fa2d4ec118abd1cb43b554c620a2e5ba]"
    GH_EMAIL: "ENCRYPTED[35c8e64311b201b83855fb2720579219835546f669c2237408ddb099b8840f3ce5ef976e191b3ed7f45d2df6355f8f14]"
    GH_CRED: "ENCRYPTED[6d2e2bb42b0ea675767bfd845e6cbe879e832e812d720fbbb4d539206c0e414d9fd6a2ab82cbb295d01dec82deb4280b]"

task:
  name: "Android Build"
  timeout_in: 480m
  container:
      image: fr05t77/ubuntu:jammy
      cpu: 8
      memory: 32G

  rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - curl -so ~/.config/rclone/rclone.conf https://$GH_CRED@raw.githubusercontent.com/frostg-012/misc/master/rclone.conf

  git_setup_script:
      - git config --global user.name "$GH_USN"
      - git config --global user.email "$GH_EMAIL"
      - echo "https://$GH_USN:$GH_CRED@github.com" > ~/.git-credentials
      - git config --global credential.helper "store --file ~/.git-credentials"

  ccache_stats_script:
      - ccache -s

  build_start_script:
      - bash build.sh
